### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/pdfhook#34]
The README and other documentation needs more details. This issue collects a number of smaller issues into one.
- [ ] Update the README to reflect the changes in the dependencies
- [ ] Examples of [use cases](https://github.com/codeforamerica/pdfhook/issues/18) for the software.
- [ ] [Questions](https://github.com/codeforamerica/pdfhook/issues/16) that have arisen from potential contributors
- [ ] The [types of PDF form fields](https://github.com/codeforamerica/pdfhook/issues/28) the app can handle
- [ ] The delivery phase [requirements](https://github.com/codeforamerica/pdfhook/issues/26) of this project
- [x] More comprehensive [setup and installation instructions](https://github.com/codeforamerica/pdfhook/issues/1) for those less familiar with Python development
- [ ] Requirements for PDFs and [instructions on preparing forms](https://github.com/codeforamerica/pdfhook/issues/10) for upload with Acrobat
